### ISSUE TITLE
Berechnung Ferien Niedersachsen 2019 Pfingsten

### ISSUE THREAD

**Issue by AndreasOKircher** [HazardDede/ferien-api#3]
Fehler bei der Berechnung Ferien in Niedersachsen 2019
Ferien in Niedersachsen für Pfingsten  gemäß Ferien-api : 
  2019-05-31 bis 2019-06-01 
auf Website des Niedersächsischen Kultusministerium : https://www.mk.niedersachsen.de/startseite/service/ferientermine/schulferien-6491.html :
 2019-05-31 (ein Tag)
 2019-06-11 (ein Tag)

**Comment by HazardDede** [comment]
@AndreasOKircher 
Hallo,
dieses Projekt ist nur ein Client für die API https://ferien-api.de/. Wir schleusen die Ergebnisse (mehr oder weniger) 1:1 durch.
Gerne (denke ich mal ;-) ) an @paulbrejla wenden, falls Ferien fehlerhaft eingetragen wurden.
