### ISSUE TITLE
No Acces To Dates Due to: ValueError: unconverted data remains: Z

### ISSUE THREAD

**Issue by OZiessler** [HazardDede/ferien-api#4]
The Ferien-Api is not working due to an internal Date error associated to strptime.
Error occurs with both syncronous an asycronous methods. The full error method has been added below:

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-24fc5505b142> in <module>
      3 
      4 #ferien.state_vacations('HH', 2019)
----> 5 vacations_2020=ferien.state_vacations("SN",2020)
      6 vacations_2019=ferien.state_vacations("SN",2019)
      7 #print(vacations_2020)

~\Anaconda3\envs\Heat_Prediction\lib\site-packages\ferien\sync_.py in state_vacations(state_code, year)
     51         )
     52 
---> 53     return _convert_json(resp)
     54 
     55 

~\Anaconda3\envs\Heat_Prediction\lib\site-packages\ferien\sync_.py in _convert_json(resp)
     20 
     21 def _convert_json(resp: APIResponse) -> List[Vacation]:
---> 22     return [Vacation.from_dict(entry) for entry in resp]
     23 
     24 

~\Anaconda3\envs\Heat_Prediction\lib\site-packages\ferien\sync_.py in <listcomp>(.0)
     20 
     21 def _convert_json(resp: APIResponse) -> List[Vacation]:
---> 22     return [Vacation.from_dict(entry) for entry in resp]
     23 
     24 

~\Anaconda3\envs\Heat_Prediction\lib\site-packages\ferien\model.py in from_dict(cls, dct)
     63 
     64         return cls(
---> 65             start=cls._parse_date(dct['start']),
     66             end=cls._parse_date(dct['end']),
     67             year=dct['year'],

~\Anaconda3\envs\Heat_Prediction\lib\site-packages\ferien\model.py in _parse_date(candidate)
     54     def _parse_date(candidate: str) -> datetime:
     55         # Parse iso format
---> 56         dt = datetime.strptime(candidate, '%Y-%m-%dT%H:%M')
     57         # All dates from the api are Europe/Berlin (CET/CEST)
     58         return TZ_GERMANY.localize(dt)

~\Anaconda3\envs\Heat_Prediction\lib\_strptime.py in _strptime_datetime(cls, data_string, format)
    575     """Return a class cls instance based on the input string and the
    576     format string."""
--> 577     tt, fraction, gmtoff_fraction = _strptime(data_string, format)
    578     tzname, gmtoff = tt[-2:]
    579     args = tt[:6] + (fraction,)

~\Anaconda3\envs\Heat_Prediction\lib\_strptime.py in _strptime(data_string, format)
    360     if len(data_string) != found.end():
    361         raise ValueError("unconverted data remains: %s" %
--> 362                           data_string[found.end():])
    363 
    364     iso_year = year = None

ValueError: unconverted data remains: Z

**Comment by paulbrejla** [comment]
Hi, 

maintainer of ferien-api here. This is likely due to the api now returning dates in the format _2021-04-05T22:00Z_ (including the Z to indicate UTC timezone) instead of _2021-04-05T22:00_. Both are valid _ISO8601_ represendations of a date.

Solutions:
- I can create an endpoint that returns dates in the 'old' format without indicating the timezone.
- This library switches from _strptime_ to _dateutil_ (https://pypi.org/project/python-dateutil/) which is way more solid.

**Comment by HazardDede** [comment]
@OZiessler Thanks for reporting this issue. I've prepared a fix: https://github.com/HazardDede/ferien-api/pull/5
@paulbrejla Thanks for making this clear. No need for a new endpoint. I will provide a fix. I will have a look at dateutil in the future. Thanks for sharing

**Comment by OZiessler** [comment]
@HazardDede Thanks for the quick update. Is the fix available in the anaconda install via pip? This would be helpful as I have integrated the api in a server framework which uses the anaconda install to incorporate the api.

**Comment by HazardDede** [comment]
> @HazardDede Thanks for the quick update. Is the fix available in the anaconda install via pip? This would be helpful as I have integrated the api in a server framework which uses the anaconda install to incorporate the api.

Yes, it should. Latest version is `0.3.6`:
https://pypi.org/project/ferien-api/
